version: "3.3"

services:
  db:
    image: postgres:11-alpine
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: seminariodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  api:
    build: ./server-prisma/
    volumes:
      - ./server-prisma:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "yarn", "start"]

  app:
    build: ./client/
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:3000"
    depends_on:
      - api
