version: 2.1
jobs:
  build:
    docker:
      - image: arvindr226/alpine-ssh

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e9:eb:83:f0:46:17:04:d9:d8:f8:0a:8d:8b:14:8f:de"
      - run:
          name: "Publish site"
          command: |
            ssh -oStrictHostKeyChecking=no connan@138.197.207.195 "touch hello2.txt" 
